# Start with `docker compose up -d`
version: '2'
services:
  app:
    image: pkiraly/metadata-qa-marc:0.7.0
    volumes:
      - ./input:/opt/qa-catalogue/marc
    ports:
      - "80:80"     # Web application
      - "8983:8983" # Solr
